[dev]
    command = "npm run start"
    publish = ".publish"
    port = 9999
    targetPort = 3000

[[redirects]]
    from = "/cors/beat-saver/*"
    to = "https://beatsaver.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/beat-saver-cdn/*"
    to = "https://eu.cdn.beatsaver.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/score-saber/*"
    to = "https://proxier324.herokuapp.com/https://scoresaber.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify", origin = "Netlify"}

[[redirects]]
    from = "/cors/score-saber-cdn/*"
    to = "https://proxier324.herokuapp.com/https://cdn.scoresaber.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify", origin = "Netlify"}