[dev]
    command = "npm run start"
    publish = ".publish"
    port = 9999
    targetPort = 3003

[[redirects]]
    from = "https://www.replay.beatleader.xyz/*"
    to = "https://replay.beatleader.xyz/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/cors/beat-saver2/*"
    to = "https://beatsaver.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/beat-saver-cdn/*"
    to = "https://eu.cdn.beatsaver.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/preview.png"
    to = "https://api.beatleader.xyz/preview/replay/"
    status = 200
    force = true
    headers = {X-From = "Netlify", origin = "Netlify"}

[[redirects]]
    from = "/cors/discord-cdn/*"
    to = "https://cdn.discordapp.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}